# Generated by Django 4.1.1 on 2024-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=200, unique_for_date="publish"),
        ),
    ]
